name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      container_name: cypress
      build:
        context: ./
        dockerfile: .docker/Dockerfile-cypress
      env_file:
        - ./env.local
        - ./env.local.cypress
      volumes:
        - ./automated_tests/e2e-cypress:/app/e2e-cypress
        - /tmp/.X11-unix:/tmp/.X11-unix
      working_dir: /app/e2e-cypress
      command: /app/start.sh
      networks:
        - gsa-gov