name: End-to-end tests
on: push
jobs:
  run-regression-tests:
    name: run-regression-tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install wait-on
      #   run: npm install wait-on -g
      # - name: Start usagov server
      #   run: |
      #     chmod +x bin/init
      #     bin/init
      # - name: Docker Compose Up
      #   run: |
      #     nohup docker compose up &
      #     wait-on http://localhost:80
      # - name: Update database
      #   run: |
      #     bin/db-update
      #     bin/drupal-update
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: automated_tests/e2e-cypress