name: Test in Docker
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # Cypress Docker image from https://hub.docker.com/r/cypress
    # with browsers pre-installed
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ".docker/Dockerfile-cypress"