name: End-to-end tests
on: push
jobs:
  setup:
    name: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install wait-on
        run: npm install wait-on -g
      - name: Start usagov server - Make the script files executable
        run: chmod +x bin/init
      - name: Run bin init
        run:  bin/init
      - name: Docker Compose Up
        run: |
          docker compose up &
          wait-on http://localhost:80 && bin/cypress-ssh
      # - name: Go to cypress directory
      #   run: wait-on http://localhost:80 && bin/cypress-ssh
      - name: Run cypress in shell
        run: npx cypress run --spec cypress/e2e



      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     working-directory: automated_tests/e2e-cypress
          #stuck- Cypress could not verify that this server is running: > http://cms-usagov.docker.local; We are verifying this server because it has been configured as your baseUrl.
