name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: automated_tests/e2e-cypress
          #stuck- Cypress could not verify that this server is running: > http://cms-usagov.docker.local; We are verifying this server because it has been configured as your baseUrl.
